### ISSUE TITLE
session_controller.rb

### ISSUE THREAD

**Issue by stefanlsd** [geoffroymontel/omniauth-deezer#6]
Not sure if im missing something, when the callback comes back I get 

uninitialized constant SessionsController

With this in my routes

  match 'auth/deezer/callback' => 'sessions#create', via: [:get, :post]

Where does this file come from? Am i doing this wrong?

**Comment by geoffroymontel** [comment]
You should define a SessionsController in your app.
Example : https://github.com/geoffroymontel/omniauth-deezer-test

The goal is to create a Session after the user is authenticated via Deezer.
For more information, please read Integrating OmniAuth Into Your Application in https://github.com/intridea/omniauth

Good luck !

**Comment by stefanlsd** [comment]
Hi.  Thanks very much for the reply!  Got it working as per you example!  Now to work out the session stuff to keep it :)
